from pydantic import BaseModel, Field
from typing import Optional, Dict, Any



class TaskOptions(BaseModel):
    files: Dict[str, str] = Field(
        default_factory=dict, description="Files to be used by the task")


class TaskResult(BaseModel):
    files: Dict[str, str] = Field(
        default_factory=dict, description="Files generated by the task")
    statistics: Dict[str, Any] = Field(
        default_factory=dict, description="Statistics generated by the task")


class Task(BaseModel):
    id: str
    type: str
    options: Optional[TaskOptions] = None
     


